<?php

declare(strict_types=1);

namespace App\Commands;

use RuntimeException;

/**
 * Compile environment and system settings into config/hot.php.
 * Hot endpoints load config/hot.php directly, avoiding Dotenv parsing at runtime.
 */
class ConfigCacheCommand
{
    public function execute(array $args = []): void
    {
        echo "Caching hot configuration...\n";

        $basePath = defined('BASE_PATH') ? BASE_PATH : dirname(__DIR__, 2);
        $configDir = $basePath . '/config';

        if (!is_dir($configDir)) {
            if (!mkdir($configDir, 0755, true) && !is_dir($configDir)) {
                throw new RuntimeException("Failed to create config directory: {$configDir}");
            }
        }

        $secret = $_ENV['APP_SECRET'] ?? '';
        if ($secret === '') {
            echo "WARNING: APP_SECRET is empty in environment. Generating a secure random secret.\n";
            $secret = bin2hex(random_bytes(32));
        }

        $config = [
            'token_secret' => $secret,
            'kid' => $_ENV['TOKEN_KID'] ?? 'v1',
            'redis_socket' => $_ENV['REDIS_SOCKET'] ?? '/var/run/redis/redis.sock',
            'redis_host' => $_ENV['REDIS_HOST'] ?? '127.0.0.1',
            'redis_port' => (int) ($_ENV['REDIS_PORT'] ?? 6379),
            'redis_password' => $_ENV['REDIS_PASSWORD'] ?? '',
            'redis_timeout' => 1.5,
            'grace_ms' => (int) ($_ENV['GRACE_MS'] ?? 3000),
            'overtime_buffer_s' => (int) ($_ENV['OVERTIME_BUFFER_S'] ?? 600),
            'company_tz' => $_ENV['COMPANY_TZ'] ?? 'Asia/Kolkata',
            'limits' => [
                'answers_rate_max' => 20,
                'answers_rate_window_s' => 10,
                'max_body_bytes' => 65536,
                'max_batch_items' => 100,
            ],
            'cached_at' => gmdate('Y-m-d H:i:s') . ' UTC',
        ];

        $export = var_export($config, true);
        $fileContent = "<?php\n\n// Auto-generated by php bin/console config:cache. Do not edit.\nreturn {$export};\n";

        $targetFile = $configDir . '/hot.php';
        file_put_contents($targetFile, $fileContent);

        echo "Configuration successfully cached at: {$targetFile}\n";
    }
}
